---
title: "Tasa de política monetaria e Inflación"
subtitle: "Comportamiento para Chile"
author: "Andrés Durán"
date: '<span style = "font-size: 70%;">`r format(Sys.Date(), format = "%A %d de %B, %Y")`</span>'
output: 
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: true
    toc_depth: 4
    number_sections: true
    theme: lumen
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=FALSE, results=FALSE, message=FALSE, warning=FALSE}
#  Seteo inicial 
rm(list = ls())
memory.size(max = T)

# Actualizar parametros
mm1 <- "enero"
mm2 <- "1"
yy  <- "2022"

# Nombre bases de datos
pi  <- "pi.xlsx"
tpm <- "tpm.xlsx"
```

```{r echo=FALSE, results=FALSE, message=FALSE, warning=FALSE}
# Librerias
library(tidyverse)
library(ggplot2)
library(readxl)
library(gganimate)
library(gapminder)
library(gifski)
library(plotly)
library(reshape2)
```

```{r echo=FALSE, results=FALSE, message=FALSE, warning=FALSE}
# Inflación variación anual 12 meses
pi <- read_excel(paste0("datos/",pi)) %>%
  janitor::clean_names()
pi <- pi[-1,c(1:2)]
colnames(pi) <- c('Periodo', 'IPC')

# Tasa de Politica Monetaria Mensual
tpm <- read_excel(paste0("datos/",tpm)) %>%
  janitor::clean_names()
tpm <- tpm[-1,c(1:2)]
colnames(tpm) <- c('Periodo', 'TPM')

# Uniendo bases desde el periodo que se encuentran y hasta donde llegan
# Filtramos la base desde 2008 en adelante
pi_tpm <- pi %>% 
  inner_join(tpm, by = c("Periodo")) %>% 
  filter(Periodo >= "2008-01-01")

pi_tpm$IPC     <- round(as.numeric(pi_tpm$IPC),2)
pi_tpm$TPM     <- round(as.numeric(pi_tpm$TPM),2)
pi_tpm$Periodo <- gsub('T00:00:00.0000000','', pi_tpm$Periodo)
pi_tpm$Y       <- as.numeric(substr(pi_tpm$Periodo,1,4))
pi_tpm$m       <- as.numeric(substr(pi_tpm$Periodo, 6,7))
pi_tpm$Periodo <- as.Date(pi_tpm$Periodo, format = '%Y-%m-%d')

# Asignando show_time & reveal_time
pi_tpm <- pi_tpm  %>% 
  mutate(show_time = ifelse((Y == 2008 & m %in% c(8,9,10)) 
                            | Y == 2021, 15, 1),
         reveal_time = cumsum(show_time))

# Reshape de base pi_tpm
pi_tpm_long <- pi_tpm %>%
  select(Periodo, IPC, TPM, reveal_time) %>%
  melt(id.vars = c("Periodo", "reveal_time"))

pi_tpm_long$Periodo <- gsub('T00:00:00.0000000','', pi_tpm_long$Periodo)
pi_tpm_long$Y       <- as.numeric(substr(pi_tpm_long$Periodo,1,4))
pi_tpm_long$m       <- as.numeric(substr(pi_tpm_long$Periodo, 6,7))
pi_tpm_long$Periodo <- as.Date(pi_tpm_long$Periodo, format = '%Y-%m-%d')

# ütlimo mes
l_pi_tpm <- pi_tpm %>%
  filter(Y == yy & m == mm2)
l_pi  <- l_pi_tpm$IPC
l_tpm <- l_pi_tpm$TPM

# Llave
ll_pi  <- ifelse(l_pi > 0, "aumentó", "disminuyó")

# Valor absoluto para llave
abs_l_pi  <- abs(l_pi)
abs_l_tpm <- abs(l_tpm)
```

Para `r mm1` la inflación anual del IPC `r ll_pi` `r l_pi`% interanualmente, mientras que la tasa de interés de política monetaria se ubica en `r l_tpm`%.

```{r echo=FALSE, results=FALSE, message=FALSE, warning=FALSE}
plot_pi_tpm <- ggplot() + 
  geom_line(data = pi_tpm
            ,aes(x = Periodo, y = IPC, group = 1
                 ,color = "IPC Total")) +
  geom_line(data = pi_tpm
            ,aes(x = Periodo, y = TPM, group = 1
                 ,color = "TPM")) + 
  scale_colour_manual("", values = c("IPC Total" = "royalblue3"
                                     ,"TPM" = "orangered3")) + 
  theme_light() + 
  labs(x = NULL, y = "Porcentaje (%)"
       ,title = "Inflación y Tasa de política monetaria"
       ,subtitle = paste0("enero 2008 - ",mm1," ", yy)
       ,caption = 'Fuente: Elaboración propia utilizando datos del INE y BCCh.') +
  scale_x_date(date_breaks = "12 months",
               limits = c(min(pi_tpm$Periodo),
                          max = max(pi_tpm$Periodo))) +
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_line(linetype="dashed"),
        panel.grid.minor.y = element_line(linetype="dashed"),
        legend.position = "bottom",
        legend.justification = "center",
        plot.caption = element_text(hjust = 0),
        plot.title = element_text(colour = "blue4", hjust = 0.5),
        plot.subtitle = element_text(colour = "blue4",hjust = 0.5),
        legend.title = element_text(colour = NA),
        panel.background = element_rect(fill = NA),
        plot.background = element_rect(fill = "white",colour = NA),
        legend.background = element_rect(fill = "white"),
        legend.direction = "horizontal",
        legend.key = element_rect(fill="white"),
        axis.text.x   = element_text(colour = "grey0"
                                      ,size = 8, angle = 90
                                      ,hjust = 1, vjust = 1));plot_pi_tpm
```


```{r echo=FALSE, results=FALSE, message=FALSE, warning=FALSE}
q <- pi_tpm_long %>% 
  ggplot(aes(x = Periodo, y = value, col = variable)) +
  geom_line(linetype = 'solid') +
  labs(x='', y = 'Porcentaje (%)',
       title = 'Inflación y Tasa de política monetaria',
       subtitle = paste0("enero 2008 - ",mm1," ", yy),
       caption = 'Fuente: Elaboración propia utilizando datos del INE y BCCh.') +
  transition_reveal(reveal_time) +
  scale_y_continuous(breaks = scales::breaks_width(2)) +
  scale_x_date(date_breaks = "12 months",
               limits = c(min(pi_tpm$Periodo),
                          max = max(pi_tpm$Periodo))) + 
               #date_labels = "%Y") + 
  scale_color_manual(name = "Variables"
                     ,labels = c("IPC total", "TPM")
    ,values = c('royalblue3','orangered3')) + 
  theme_light() + 
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_line(linetype="dashed"),
        panel.grid.minor.y = element_line(linetype="dashed"),
        legend.position = "bottom",
        legend.justification = "center",
        plot.caption = element_text(hjust = 0),
        plot.title = element_text(colour = "blue4", hjust = 0.5),
        plot.subtitle = element_text(colour = "blue4",hjust = 0.5),
        legend.title = element_text(colour = NA),
        panel.background = element_rect(fill = NA),
        plot.background = element_rect(fill = "white",colour = NA),
        legend.background = element_rect(fill = "white"),
        legend.direction = "horizontal",
        legend.key = element_rect(fill="white"),
        axis.text.x   = element_text(colour = "grey0"
                                      ,size = 8, angle = 90
                                      ,hjust = 1, vjust = 1))

animate(q, duration = 5, fps = 20
        , width = 500, height = 500
        , renderer = gifski_renderer())

anim_save("inflation_tpm_chile.gif")

```


